
  
version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.$ENVIRONMENT
    image: backend:latest
    ports:
      - 3000:3000
    restart: always

  mongo:
    image: mongo
    container_name: coffebreak-mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env

