FROM node:16.15.0-alpine as build

RUN mkdir -p /app

WORKDIR /app

COPY . .

RUN yarn install

RUN yarn run build


FROM node:16.15.0-alpine as dist

RUN mkdir -p /app

WORKDIR /app

COPY --from=build /app/node_modules /app/node_modules

COPY --from=build /app/dist /app/dist
COPY --from=build /app/.env /app/.env


CMD [ "node", "dist/main.js" ]

