

name: test
on:
  push:
    branches:
      - main
    tags: 
      - coffebreak
      - local
jobs:
  test1:    
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3   

      - name: check who am i
        run: echo "I am $(whoami)"

      - name: build containers
        run: docker-compose -f docker-compose.dev.yml up -d